spring.application.name=learnJpa

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_spring?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=create for creating table using jpa hibernate

#this is to show sql query

spring.jpa.show-sql=true